name = "CloudflareR2"
uuid = "7a9847aa-5741-445f-924a-8fbee339cc15"
authors = ["Agustín Covarrubias", "Expanding Man <savastio@protonmail.com> and contributors"]
version = "1.0.1"

[deps]
AWS = "fbe9abb3-538b-5e4e-ba9e-bc94f4f92ebc"
AWSS3 = "1c724243-ef5b-51ab-93f4-b0a88ac62a95"
FilePathsBase = "48062228-2e41-5def-b9a4-89aafe57970f"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
URIs = "5c2747f8-b7ea-4ff2-ba2e-563bfd36b1d4"

[compat]
AWS = "1.25"
AWSS3 = "0.8.3, 0.9, 0.10"
FilePathsBase = "0.9"
URIs = "1"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
